name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.pnchau}}
          password: ${{secrets.dckr_pat_UPAkHKk7DInrNKX14GlsK7QkyEk}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # This will tag the image as <dockerhub-username>/<repo-name>:latest
          tags: ${{secrets.pnchau}}/userm:latest
