name: Build and Deploy Container to ACR and Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: moosefactoryuser
      IMAGE_NAME: moosefactoryuser
      ACR_LOGIN_SERVER: moosefactoryuser.azurecr.io
      APP_NAME: MooseFactoryUserManagment
      RESOURCE_GROUP: MooseFactoryUserManagment_group
      
      AZURE_CREDENTIALS: '{
            "clientId": "d09596e5-b157-45e3-b8cf-1e49844276f6",
            "clientSecret": "lN18Q~_yJnB2rSELcYuV~fgwWtxKrIG1YYJrsach",
            "subscriptionId": "e6db8f7f-6fb1-4845-9d9d-df9f7b68cbb7",
            "tenantId": "170bbabd-a2f0-4c90-ad4b-0e8f0f0c4259",
            "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
            "resourceManagerEndpointUrl": "https://management.azure.com/",
            "activeDirectoryGraphResourceId": "https://graph.windows.net/",
            "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
            "galleryEndpointUrl": "https://gallery.azure.com/",
            "managementEndpointUrl": "https://management.core.windows.net/"
         }'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}

      - name: Build Docker Image
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

      - name: Deploy to Azure App Service using the Container Image
        run: |
          az webapp config container set \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
            --docker-registry-server-url https://$ACR_LOGIN_SERVER
          az webapp restart --name $APP_NAME --resource-group $RESOURCE_GROUP
