name: Build and Deploy Container to ACR and Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME:         moosefactoryuser
      ACR_LOGIN_SERVER: moosefactoryuser.azurecr.io
      IMAGE_NAME:       moosefactoryuser
      APP_NAME:         MooseFactoryUserManagment
      RESOURCE_GROUP:   MooseFactoryUserManagment_group

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (inline creds)
        uses: azure/login@v1
        with:
          creds: >-
            {
              "clientId":"d09596e5-b157-45e3-b8cf-1e49844276f6",
              "clientSecret":"lN18Q~_yJnB2rSELcYuV~fgwWtxKrIG1YYJrsach",
              "subscriptionId":"e6db8f7f-6fb1-4845-9d9d-df9f7b68cbb7",
              "tenantId":"170bbabd-a2f0-4c90-ad4b-0e8f0f0c4259",
              "activeDirectoryEndpointUrl":"https://login.microsoftonline.com",
              "resourceManagerEndpointUrl":"https://management.azure.com/",
              "activeDirectoryGraphResourceId":"https://graph.windows.net/",
              "sqlManagementEndpointUrl":"https://management.core.windows.net:8443/",
              "galleryEndpointUrl":"https://gallery.azure.com/",
              "managementEndpointUrl":"https://management.core.windows.net/"
            }

      - name: Login to ACR via Azure CLI
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push to ACR
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Configure Web App to use new image
        run: |
          az webapp config container set \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest \
            --docker-registry-server-url https://${{ env.ACR_LOGIN_SERVER }}

      - name: Restart Web App
        run: |
          az webapp restart \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }}

